# Generated by Django 3.0.9 on 2020-08-07 08:55

from django.db import migrations, models


def calculate_unix_start_and_end_times(apps, schema_editor):
    WorkTimes = apps.get_model('work_time', 'WorkTime')
    for work_time in WorkTimes.objects.all().iterator():
        if work_time.start_time is not None:
            work_time.start_unix_time = int((work_time.start_time).total_seconds())
        if work_time.end_time is not None:
            work_time.end_unix_time = int((work_time.end_time).total_seconds())
        work_time.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('work_time', '0002_added_work_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='end_unix_time',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='worktime',
            name='start_unix_time',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),

        migrations.RunPython(calculate_unix_start_and_end_times, reverse_func),

        migrations.AlterField(
            model_name='worktime',
            name='start_unix_time',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
