# Generated by Django 3.0.9 on 2020-08-07 11:21

from django.db import migrations, models


def calculate_start_and_end_days(apps, schema_editor):
    WorkTimes = apps.get_model('work_time', 'WorkTime')
    for work_time in WorkTimes.objects.all().iterator():
        if work_time.start_unix_time is not None:
            work_time.days_count = work_time.start_unix_time / 86400
            work_time.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('work_time', '0003_added_unix_start_and_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='days_count',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),

        migrations.RunPython(calculate_start_and_end_days, reverse_func),

        migrations.AlterField(
            model_name='worktime',
            name='days_count',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
