# Generated by Django 3.1 on 2020-08-12 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_time', '0004_added_days_count_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 12, 16, 34, 14, 572268, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktime',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 8, 12, 16, 34, 27, 220201, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktime',
            name='unix_end_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktime',
            name='unix_start_time',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktime',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),


        migrations.AlterModelOptions(
            name='worktime',
            options={'ordering': ['-start_date', '-unix_start_time']},
        ),


        migrations.RemoveField(
            model_name='worktime',
            name='days_count',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='end_unix_time',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='start_unix_time',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='work_time',
        ),
    ]
