# Generated by Django 3.1.1 on 2020-09-06 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_time', '0005_refactored_the_model_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktime',
            options={'ordering': ['-start_datetime']},
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='unix_end_time',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='unix_start_time',
        ),
        migrations.AddField(
            model_name='worktime',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktime',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 14, 50, 39, 506003, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
