# Generated by Django 3.1.1 on 2020-09-13 16:36

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work_time', '0006_replaced_unix_time_with_DateTime_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worktime',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='worktime',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.RenameField(
            model_name='worktime',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='worktime',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
