# Generated by Django 3.0.9 on 2020-08-07 05:41

from django.db import migrations, models
import django.utils.timezone
from time_tracking.event.models import Event

def set_my_defaults(apps, schema_editor):
    Events = apps.get_model('event', 'Event')
    for event in Events.objects.all().iterator():
        event.end_date = event.end_time.date()
        event.start_date = event.start_time.date()
        event.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(null=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(null=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),


        migrations.RunPython(set_my_defaults, reverse_func),


        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),



        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
