# Generated by Django 3.1.1 on 2020-09-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_added_created_at_and_updated_at_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
