# Generated by Django 3.1.1 on 2020-09-13 16:50

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_updated_the_description_to_not_nullable_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.RenameField(
            model_name='event',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='event',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
