# Generated by Django 3.1.1 on 2020-09-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0002_added_created_at_and_updated_at_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='brief_description',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
