# Generated by Django 3.1.1 on 2020-09-09 23:35

import datetime
from datetime import timedelta
from django.db import migrations, models
from django.utils.timezone import utc


def calculate_start_and_end_days(apps, schema_editor):
    Vacation = apps.get_model('vacation', 'Vacation')
    for vacation in Vacation.objects.all().iterator():
        if vacation.end_date is None:
            vacation.end_date = vacation.start_date + timedelta(vacation.number_of_days)
            vacation.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0003_updated_the_brief_description_to_not_nullable_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.RunPython(calculate_start_and_end_days, reverse_func),
        migrations.RemoveField(
            model_name='vacation',
            name='number_of_days',
        ),
        migrations.AlterField(
            model_name='vacation',
            name='end_date',
            field=models.DateField(),
        ),
    ]


