# Generated by Django 3.1.1 on 2020-09-13 16:46

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0004_replaced_number_of_days_field_wtih_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='vacation',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='vacation',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
